jdillard/sphinx-sitemap

- sphinx_sitemap/__init__.py
Removing this will allow the extension to work with any other extension that overrides HTMLTranslator. It's also not needed. Tested and works fine.
> Don't set HTMLTranslator, which causes conflicts

- .gitignore
- CONTRIBUTING.md
- sphinx_sitemap/__init__.py
- tox.ini
Let's imagine a project with the following documentation structure:
```
index.rst
faq.rst
downloads/index.rst
downloads/linux.rst
```
`sphinx-sitemap` would generate a sitemap with:
```
https://example.com/index.html
https://example.com/faq.html
https://example.com/downloads/index.html
https://example.com/downloads/linux.html
```
But as we are using `DirectoryHTMLBuilder`, Sphinx will actually build:
```
https://example.com/index.html
https://example.com/faq/index.html              <- wrong in sitemap
https://example.com/downloads/index.html
https://example.com/downloads/linux/index.html  <- wrong in sitemap
```
And thus, as we want to use "directory" style URLs:
```
https://example.com/
https://example.com/faq/
https://example.com/downloads/
https://example.com/downloads/linux/
```
Which …
> Support for DirectoryHTMLBuilder

- sphinx_sitemap/__init__.py
Allowing to use a custom i18n_url_scheme parameter.
Before this commit, the URLs were forced to use the format
`<site>/<lang>/<version>/<link>` which is the format used by RTD but
some may use a different one.
Fixes jdillard/sphinx-sitemap#22
> [IMP] allow custom URL scheme for internationalized pages

- sphinx_sitemap/__init__.py
resolves #8 
I hope this is correct. This is the first python code that I wrote.
> add configuration value for sitemap.xml filename

- README.rst
- sphinx_sitemap/__init__.py
I propose to add the `sitemap_locales` configuration option to manually set locales that will show in the sitemap as alternates to page.
I've started to use sphinx-sitemap for my blog at https://blog.documatt.com. It's a single language and likely will stay. It's Sphinx with Ablog extension for blogging. It's a great extension that comes with many supported locales like Chinese, Korean, Spain, etc.
Unfortunately, it means that if another extension like sphinx-sitemap asks for `app.builder.config.locale_dirs`, the result is a long list of locale_dirs. Former `get_locales()` will then result in the same long list of locales. But they come from third-party extension!
So I add the `sitemap_locales` option to manually override locales which I need/want to list in sitemaps. By default, nothing …
> sitemap_locales option

- .pre-commit-config.yaml
- pyproject.toml
- setup.py
- sphinx_sitemap/__init__.py
- tox.ini
Install pre-commit with `isort`, `black`, and `flake8`.
> Install pre-commit with isort, black, and flake8

- README.rst
- Use code highlighting
- Split the installation and configuring sections
- Move URL scheme to top of configuration section
- Improve the wording of the URL scheme to mention the changed language behavior in Sphinx 5 (https://github.com/jdillard/sphinx-sitemap/issues/33)
[README](https://github.com/jdillard/sphinx-sitemap/blob/feature/improve-readme/README.rst)
> Improve the wording of the README

- README.rst
- sphinx_sitemap/__init__.py
- Remove check for current language so that multilingual sitemap's follow [proper formatting](https://developers.google.com/search/docs/advanced/crawling/localized-versions#sitemap).
- Fix README sitemap example.
Closes https://github.com/jdillard/sphinx-sitemap/issues/30
> Follow correct format for multilingual sitemaps

- .github/workflows/continuous-integration.yml
- tox.ini
- Add python 3.10 tests
- Remove `flake8` test since it was made redundant with `pre-commit`
> Add python 3.10 tests and remove flake8 test from tox

- CHANGELOG.md
- sphinx_sitemap/__init__.py
- Use logging for all logging messages (instead of `print`)
> Use logging for all logging messages

- docs/changelog.rst
- sphinx_sitemap/__init__.py
- Have `get_locales` return a value
- Remove unneeded `if` statement
- Move `sitemap_links` to `app.builder.env`
- Clean up XML creation
- Clean up `DirectoryHTMLBuilder` support
- Mark `parallel_read_safe` as `True`
> General code clean up

- README.rst
- docs/changelog.rst
- docs/index.rst
- sphinx_sitemap/__init__.py
- tests/roots/test-root/dolor.rst
- tests/roots/test-root/elitr.rst
- tests/roots/test-root/ipsum.rst
- tests/roots/test-root/lorem.rst
- tests/test_parallel_mode.py
- tests/test_simple.py
- Add support for parallel mode
Huge shout-out to @xmo-odoo for https://github.com/jdillard/sphinx-sitemap/pull/29 (closed so couldn't merge).
Future improvements to detecting when parallel mode is turned on could be made, as mentioned in the PR:
> This is achieved by storing a queue in the env so the "write" workers can shove page names in there (sadly multiprocessing.Queue did not work as it apparently doesn't like the way the workers are created), and create_sitemap can then pop all that from the queue.
>
> Anyway there's a bit of an issue here, probably not a huge one because sitemap is only invoked once per document (not hundreds of times per), but the multiprocessing queue is always created and possibly somewhat heavy (it's at least a separate process, plus whatever the proxies use …
> :sparkles: NEW: Add support for parallel mode

- docs/changelog.rst
- sphinx_sitemap/__init__.py
- tests/test_simple.py
- Add tests for `dirhtml` builder
> :test_tube: TESTS: Add tests for dirhtml builder

- docs/changelog.rst
- requirements_dev.txt
- setup.cfg
The contents of `.whl` archive no longer include the `tests` and `docs` directory content:
```console
Length      Date    Time    Name
---------  ---------- -----   ----
5969  2022-12-26 01:18   sphinx_sitemap/__init__.py
1070  2022-12-26 01:27   sphinx_sitemap-2.4.0.dist-info/LICENSE
2681  2022-12-26 01:27   sphinx_sitemap-2.4.0.dist-info/METADATA
92  2022-12-26 01:27   sphinx_sitemap-2.4.0.dist-info/WHEEL
15  2022-12-26 01:27   sphinx_sitemap-2.4.0.dist-info/top_level.txt
504  2022-12-26 01:27   sphinx_sitemap-2.4.0.dist-info/RECORD
---------                     -------
10331                     6 files
```
- Fix wheel includes
- Add `build` package
Closes https://github.com/jdillard/sphinx-sitemap/issues/50
> :bug: FIX: Fix wheel includes so they don't include docs and tests

- CHANGELOG.rst
- tox.ini
> :test_tube: TESTS: Add Sphinx 6 env to tox

- sphinx_sitemap/__init__.py
As reported in #56, here is a trivial one-liner pull request to fix the issue.
> Fix to respect the sphinx config "html_file_suffix".

- CHANGELOG.rst
- docs/_vale/ignore_words.txt
- docs/index.rst
- docs/search-optimization.rst
- Add docs on site search optimization
- Rename `search-engine-optimization` to a more general `search-optimization`
> :books: DOCS: Add site search optimization

- CHANGELOG.rst
- sphinx_sitemap/__init__.py
Incremental builds with this extension are currently broken. #47 added support for parallel building via a multiprocessing.Manager().Queue() proxy object attached to the Environment. Sphinx later pickles the Environment object, including the Queue proxy object. The object pickles successfully, but when the Environment is later unpickled to determine if an incremental build can be used, the proxy object tries to reconnect to the server process that existed at the time of pickling, but no longer exists. This failure is near-silently swallowed with an unintuitive error message and sphinx proceeds with a full rebuild:
```
$ sphinx-build docs/ _build -b html -T -D html_baseurl=https://example.com
Running Sphinx v6.1.3
loading pickled environment... failed
failed: [Errno 2] No such file or …
```
> :bug: FIX: Fix incremental building by preventing multiprocessing queue from being pickled with environment

- CHANGELOG.rst
- sphinx_sitemap/__init__.py
- Add docstrings
- Add type hints
Taken from the following work by @neflyte:
- https://github.com/mattermost/docs/pull/5038
Co-authored-by: Alan Lew <alan@ethereal.cc>
> :wrench: MAINT: Add docstrings and type hints

- .github/workflows/continuous-integration.yml
- sphinx_sitemap/__init__.py
- tests/test_parallel_mode.py
- tests/test_simple.py
> FIX: Fix Path use for Sphinx 7.2

- CHANGELOG.rst
- tests/conftest.py
- tox.ini
```
sphinx-sitemap/tests/conftest.py:2: RemovedInSphinx90Warning: 'sphinx.testing.path' is deprecated. Use 'os.path' or 'pathlib'
```
- Replace `sphinx.testing.path` with `Path`
- Drop test support for Sphinx 2, 3 and 4.
> :wrench: MAINT: Fix deprecated sphinx.testing.path

- pyproject.toml
Required for compatability with setuptools >= 69.
> Declare 'dependencies' as 'dynamic'

- .github/workflows/continuous-integration.yml
- CHANGELOG.rst
- docs/requirements.txt
- docs/source/advanced-configuration.rst
- docs/source/conf.py
- docs/source/configuration-values.rst
- pyproject.toml
- sphinx_sitemap/__init__.py
- tests/test_simple.py
- tox.ini
Fixes https://github.com/jdillard/sphinx-sitemap/issues/2
- Add `sitemap_excludes` config option (including docs and tests)
- Drop testing support for Python 3.7 and add support for 3.12
- Fix existing tox testing errors for Sphinx 7
- https://sphinx-sitemap--91.org.readthedocs.build/en/91/
> :sparkles: NEW: Add sitemap_excludes configuration
